version: '3.9'

services:
  panorama_video_website:
    image: patrol-robot-admin:latest
    container_name: patrol-robot-admin
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./build:/patrol-robot-admin
    restart: always
