version: '3.9'

services:
  panorama-robot-admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: patrol-robot-admin
    image: nginx:latest
    container_name: patrol-robot-admin
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./build:/patrol-robot-admin
    restart: always
